hash-format = "sha256"

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/advanced-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
metafile = true

[[files]]
file = "mods/auudio-forge.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/baubley-heart-canisters.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/colorful-hearts.pw.toml"
metafile = true

[[files]]
file = "mods/configuration.pw.toml"
metafile = true

[[files]]
file = "mods/construction-wand.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.pw.toml"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/ender-io.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fancymenu-forge.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
metafile = true

[[files]]
file = "mods/fastsuite.pw.toml"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-essentials-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-quests-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
metafile = true

[[files]]
file = "mods/greate.pw.toml"
metafile = true

[[files]]
file = "mods/gregtechceu-modern.pw.toml"
metafile = true

[[files]]
file = "mods/guard-villagers.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-hud-forge.pw.toml"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs-create.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/load-my-resources-forge.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/more-red-x-cc-tweaked-compat.pw.toml"
metafile = true

[[files]]
file = "mods/more-red.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/nethers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
metafile = true

[[files]]
file = "mods/openblocks-elevator.pw.toml"
metafile = true

[[files]]
file = "mods/openblocks-trophies.pw.toml"
metafile = true

[[files]]
file = "mods/oreberries-replanted.pw.toml"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
metafile = true

[[files]]
file = "mods/probejs.pw.toml"
metafile = true

[[files]]
file = "mods/productivebees.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
metafile = true

[[files]]
file = "mods/spice-of-life-carrot-edition.pw.toml"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/toast-control.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
metafile = true

[[files]]
file = "mods/yeetusexperimentus.pw.toml"
metafile = true
