hash-format = "sha256"

[[files]]
file = "config/ftbquests/quests/chapter_groups.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/ulvuls__humble_beginnigs.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/welcome.snbt"

[[files]]
file = "config/ftbquests/quests/chapters/you_gotta_start_somewhere.snbt"

[[files]]
file = "config/ftbquests/quests/data.snbt"

[[files]]
file = "defaultconfigs/ftbchunks/client-config.snbt"

[[files]]
file = "defaultconfigs/ftbchunks/ftbchunks-world.snbt"

[[files]]
file = "defaultconfigs/ftbessentials-server.snbt"

[[files]]
file = "defaultconfigs/toms_storage-server.toml"

[[files]]
file = "kubejs/README.txt"

[[files]]
file = "kubejs/assets/gtceu/lang/en_us.json"

[[files]]
file = "kubejs/assets/kubejs/textures/item/drinkable_liquid_concrete.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/empty_compass.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_advanced_integrated_circuit.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_advanced_integrated_circuit_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_basic_electronic_circuit.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_basic_integrated_circuit.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_good_electronic_circuit.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_good_integrated_circuit.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_conveyor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_conveyor_module_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_electric_motor_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_electric_piston_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_electric_pump_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_emitter.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_emitter_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_fluid_regulator.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_fluid_regulator_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_motor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_piston.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_pump.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_robot_arm.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_robot_arm_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_sensor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_hv_sensor_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_inter_nano_processor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_inter_nano_processor_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_lv_conveyor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_lv_emitter.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_lv_fluid_regulator.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_lv_motor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_lv_piston.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_lv_pump.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_lv_robot_arm.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_lv_sensor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_micro_processor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_micro_processor_assembly.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_microchip_processor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_mv_conveyor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_mv_emitter.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_mv_fluid_regulator.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_mv_motor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_mv_piston.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_mv_pump.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_mv_robot_arm.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_mv_sensor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_nano_processor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_nano_processor_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inc_raw_resin_printed_circuit_board_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inter_micro_processor_assembly.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/inter_nano_processor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/netherite_plate_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/plate.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/plate_1.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/plate_2.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/plate_3.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/raw_epoxy_circuit_board.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/raw_integrated_circuit_board.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/raw_phenolic_circuit_board.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/raw_phenolic_printed_circuit_board_show.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/raw_plastic_circuit_board.png"

[[files]]
file = "kubejs/client_scripts/rei_hide.js"

[[files]]
file = "kubejs/config/client.properties"

[[files]]
file = "kubejs/config/common.properties"

[[files]]
file = "kubejs/config/probejs.json"

[[files]]
file = "kubejs/jsconfig.json"

[[files]]
file = "kubejs/server_scripts/Armor/AD Astra/JetSuit.js"

[[files]]
file = "kubejs/server_scripts/Armor/AD Astra/NetheriteSpaceSuit.js"

[[files]]
file = "kubejs/server_scripts/Armor/AD Astra/SpaceSuit.js"

[[files]]
file = "kubejs/server_scripts/Armor/Create/CopperDiving.js"

[[files]]
file = "kubejs/server_scripts/Armor/Create/NetheriteDiving.js"

[[files]]
file = "kubejs/server_scripts/Armor/Vanilla/Chain.js"

[[files]]
file = "kubejs/server_scripts/Armor/Vanilla/Diamond.js"

[[files]]
file = "kubejs/server_scripts/Armor/Vanilla/Gold.js"

[[files]]
file = "kubejs/server_scripts/Armor/Vanilla/Iron.js"

[[files]]
file = "kubejs/server_scripts/Armor/Vanilla/Leather.js"

[[files]]
file = "kubejs/server_scripts/Armor/Vanilla/Netherite.js"

[[files]]
file = "kubejs/server_scripts/GregMultiRecipe.js"

[[files]]
file = "kubejs/server_scripts/Items/Compass.js"

[[files]]
file = "kubejs/server_scripts/Items/Piston.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/AE2/cutting_16k_wafer.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/AE2/cutting_1k_wafer.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/AE2/cutting_256k_wafer.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/AE2/cutting_4k_wafer.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/AE2/cutting_64k_wafer.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Ad_Astra/T1Rocket.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Ad_Astra/T2Rocket.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Ad_Astra/T3Rocket.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Ad_Astra/T4Rocket.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Greg/Circuit Assembler/HVCircuits.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Greg/Engraver/engraverNaquadah.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Greg/Engraver/engraverNeutronium.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Greg/Engraver/engraverPhosphorus.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Greg/Engraver/engraverSilicon.js"

[[files]]
file = "kubejs/server_scripts/JSONRecipes/Greg/bender.js"

[[files]]
file = "kubejs/server_scripts/Mods/AE2.js"

[[files]]
file = "kubejs/server_scripts/Mods/Avaritia.js"

[[files]]
file = "kubejs/server_scripts/Mods/Create.js"

[[files]]
file = "kubejs/server_scripts/Mods/EnderStorage.js"

[[files]]
file = "kubejs/server_scripts/Mods/Greate.js"

[[files]]
file = "kubejs/server_scripts/Mods/Greg.js"

[[files]]
file = "kubejs/server_scripts/Mods/IronChest.js"

[[files]]
file = "kubejs/server_scripts/Mods/SophisticatedBackpacks.js"

[[files]]
file = "kubejs/server_scripts/Mods/TomsSimpleStorage.js"

[[files]]
file = "kubejs/server_scripts/Mods/TwilightForest.js"

[[files]]
file = "kubejs/server_scripts/Mods/Wands.js"

[[files]]
file = "kubejs/server_scripts/Mods/ad_astra.js"

[[files]]
file = "kubejs/server_scripts/SequencedAssembly/AE2sequence.js"

[[files]]
file = "kubejs/server_scripts/SequencedAssembly/HV.js"

[[files]]
file = "kubejs/server_scripts/SequencedAssembly/IntermediateItems.js"

[[files]]
file = "kubejs/server_scripts/SequencedAssembly/LV.js"

[[files]]
file = "kubejs/server_scripts/SequencedAssembly/MV.js"

[[files]]
file = "kubejs/server_scripts/Tags.js"

[[files]]
file = "kubejs/server_scripts/Vanilla.js"

[[files]]
file = "kubejs/startup_scripts/BlockGeneration.js"

[[files]]
file = "kubejs/startup_scripts/ItemGeneration.js"

[[files]]
file = "kubejs/startup_scripts/ItemsModification.js"

[[files]]
file = "kubejs/startup_scripts/MultiBlock.js"

[[files]]
file = "kubejs/startup_scripts/Ores.js"

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/advanced-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
metafile = true

[[files]]
file = "mods/auudio-forge.pw.toml"
metafile = true

[[files]]
file = "mods/avaritia-lite.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/baubley-heart-canisters.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
metafile = true

[[files]]
file = "mods/colorful-hearts.pw.toml"
metafile = true

[[files]]
file = "mods/configuration.pw.toml"
metafile = true

[[files]]
file = "mods/construction-wand.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.pw.toml"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/darker-depths.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/fancymenu-forge.pw.toml"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
metafile = true

[[files]]
file = "mods/fastsuite.pw.toml"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-essentials-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-quests-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
metafile = true

[[files]]
file = "mods/greate.pw.toml"
metafile = true

[[files]]
file = "mods/gregtechceu-modern.pw.toml"
metafile = true

[[files]]
file = "mods/guard-villagers.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-hud-forge.pw.toml"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
metafile = true

[[files]]
file = "mods/item-filters.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/kleeslabs.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs-create.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/lazy-dfu-forge.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/more-red-x-cc-tweaked-compat.pw.toml"
metafile = true

[[files]]
file = "mods/more-red.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
metafile = true

[[files]]
file = "mods/openblocks-elevator.pw.toml"
metafile = true

[[files]]
file = "mods/openblocks-trophies.pw.toml"
metafile = true

[[files]]
file = "mods/oreberries-replanted.pw.toml"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-crops.pw.toml"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-core.pw.toml"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-extended.pw.toml"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-trees.pw.toml"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
metafile = true

[[files]]
file = "mods/polylib.pw.toml"
metafile = true

[[files]]
file = "mods/probejs.pw.toml"
metafile = true

[[files]]
file = "mods/productivebees.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/rubidium.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
metafile = true

[[files]]
file = "mods/spice-of-life-carrot-edition.pw.toml"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
metafile = true

[[files]]
file = "mods/swingthroughgrass.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
metafile = true

[[files]]
file = "mods/toast-control.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
metafile = true

[[files]]
file = "mods/yeetusexperimentus.pw.toml"
metafile = true

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/accessibility.json"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/language.json"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/mods.json"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/multiplayer.json"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/options.json"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/quit.json"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/reloadbutton.json"

[[files]]
file = "packmenu/resources/assets/packmenu/buttons/singleplayer.json"

[[files]]
file = "packmenu/resources/assets/packmenu/lang/en_us.json"

[[files]]
file = "packmenu/resources/assets/packmenu/textures/gui/background.png"

[[files]]
file = "packmenu/resources/assets/packmenu/textures/gui/reload.png"

[[files]]
file = "packmenu/resources/assets/packmenu/textures/gui/widgets.png"

[[files]]
file = "packmenu/resources/pack.mcmeta"

[[files]]
file = "packmenu/resources/pack.png"
