name = "GreateBTH"
author = "Greators of Greate"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
forge = "47.1.47"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
