name = "GreateBTH"
author = "Greators of Greate"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0c3a824f12ea44a99525370c05f683e8c9091beb9e7026dbebc57a4aac063d5"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
