ServerEvents.recipes(event => {
    event.recipes.gbthcore.bloomery("kubejs:copper_bloom")
        .duration(600)
        .itemInputs('#forge:raw_materials/copper')
        .itemInputs('minecraft:charcoal')
        .itemOutputs('kubejs:copper_bloom')

    event.recipes.gbthcore.bloomery("kubejs:copper_bloom_1")
        .duration(600)
        .itemInputs('#forge:raw_materials/chalcopyrite')
        .itemInputs('minecraft:charcoal')
        .itemOutputs('kubejs:copper_bloom')

    event.recipes.gbthcore.bloomery("kubejs:tin_bloom")
        .duration(600)
        .itemInputs('#forge:raw_materials/tin')
        .itemInputs('minecraft:charcoal')
        .itemOutputs('kubejs:tin_bloom')

    event.recipes.gbthcore.bloomery("kubejs:tin_bloom_1")
        .duration(600)
        .itemInputs('#forge:raw_materials/cassiterite')
        .itemInputs('minecraft:charcoal')
        .itemOutputs('kubejs:tin_bloom')

    event.recipes.gbthcore.bloomery("kubejs:tin_bloom_2")
        .duration(600)
        .itemInputs('#forge:raw_materials/cassiterite_sand')
        .itemInputs('minecraft:charcoal')
        .itemOutputs('kubejs:tin_bloom')

    event.recipes.gbthcore.bloomery("kubejs:bronze_bloom")
        .duration(900)
        .itemInputs('3x minecraft:copper_ingot')
        .itemInputs('gtceu:tin_ingot')
        .itemInputs('2x minecraft:charcoal')
        .itemOutputs('4x kubejs:bronze_bloom')

    event.recipes.gbthcore.bloomery("kubejs:wrought_iron_bloom")
        .duration(600)
        .itemInputs('#forge:raw_materials/iron')
        .itemInputs('minecraft:charcoal')
        .itemOutputs('kubejs:wrought_iron_bloom')

    event.recipes.gbthcore.bloomery("kubejs:wrought_iron_bloom_1")
        .duration(600)
        .itemInputs('#forge:raw_materials/pyrite')
        .itemInputs('minecraft:charcoal')
        .itemOutputs('kubejs:wrought_iron_bloom')
})