ServerEvents.recipes(event => {
	let remove = [
		'create:andesite_casing',
		'create:belt_connector',
		'create:brass_hand',
		'create:cogwheel',
		'create:fluid_pipe',
		'create:fluid_valve',
		'create:hand_crank',
		'create:large_cogwheel',
		'create:large_water_wheel',
		'create:mechanical_pump',
		'create:ndesite_alloy',
		'create:pressing/sugar_cane',
		'create:raw_zinc_block',		
		'create:smart_fluid_pipe', 
		'create:steam_engine',
		'create:water_wheel',
		'create:windmill_bearing',
		'gtceu:flint_axe',
		'gtceu:flint_hoe',
		'gtceu:flint_knife',
		'gtceu:flint_pickaxe',
		'gtceu:flint_shovel',
		'gtceu:flint_sword',
		'gtceu:shaped/vacuum_tube',
		'gtceu:shapeless/rubber_wood_planks',
		'gtceu:smelting/sticky_resin_from_slime',
		'minecraft:bamboo_mosaic_slab',
		'minecraft:bamboo_planks',
		'minecraft:barrel',
		'minecraft:blast_furnace',
		'minecraft:cartography_table',
		'minecraft:chest',
		'minecraft:compass',
		'minecraft:composter',
		'minecraft:crafting_table',
		'minecraft:ender_chest',
		'minecraft:furnace',
		'minecraft:grindstone',
		'minecraft:lectern',
		'minecraft:loom',
		'minecraft:mud_bricks',
		'minecraft:netherite_ingot',
		'minecraft:packed_mud',
		'minecraft:raw_copper_block',
		'minecraft:raw_gold_block',
		'minecraft:raw_iron_block',
		'minecraft:smithing_table',
		'minecraft:smoker',
		'minecraft:stonecutter',
		]

	remove.forEach(recipe => {
		event.remove({id: recipe})
	})
})