ServerEvents.recipes(event => {
    //Naquadah
    event.recipes.gtceu.laser_engraver('kubejs:engraving_1k_me_storage_wafer_naquadah')
        .duration(200)
        .itemInputs('gtceu:naquadah_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('8x kubejs:1k_me_storage_wafer')
        .circuit(1)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_4k_me_storage_wafer_naquadah')
        .duration(200)
        .itemInputs('gtceu:naquadah_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('8x kubejs:4k_me_storage_wafer')
        .circuit(2)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_16k_me_storage_wafer_naquadah')
        .duration(200)
        .itemInputs('gtceu:naquadah_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('8x kubejs:16k_me_storage_wafer')
        .circuit(3)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_64k_me_storage_wafer_naquadah')
        .duration(200)
        .itemInputs('gtceu:naquadah_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('4x kubejs:64k_me_storage_wafer')
        .circuit(4)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_256k_me_storage_wafer_naquadah')
        .duration(200)
        .itemInputs('gtceu:naquadah_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('kubejs:256k_me_storage_wafer')
        .circuit(5)
        .EUt(1920)


    //Neutronium
    event.recipes.gtceu.laser_engraver('kubejs:engraving_1k_me_storage_wafer_neutronium')
        .duration(50)
        .itemInputs('gtceu:neutronium_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('16x kubejs:1k_me_storage_wafer')
        .circuit(1)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_4k_me_storage_wafer_neutronium')
        .duration(50)
        .itemInputs('gtceu:neutronium_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('16x kubejs:4k_me_storage_wafer')
        .circuit(2)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_16k_me_storage_wafer_neutronium')
        .duration(50)
        .itemInputs('gtceu:neutronium_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('16x kubejs:16k_me_storage_wafer')
        .circuit(3)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_64k_me_storage_wafer_neutronium')
        .duration(50)
        .itemInputs('gtceu:neutronium_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('8x kubejs:64k_me_storage_wafer')
        .circuit(4)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_256k_me_storage_wafer_neutronium')
        .duration(50)
        .itemInputs('gtceu:neutronium_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('2x kubejs:256k_me_storage_wafer')
        .circuit(5)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_infinity_me_storage_wafer_neutronium')
        .duration(9000)
        .itemInputs('gtceu:neutronium_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('kubejs:256k_me_storage_wafer')
        .circuit(6)
        .EUt(135000000)

    //Phosphourus
    event.recipes.gtceu.laser_engraver('kubejs:engraving_1k_me_storage_wafer_phosphorus')
        .duration(500)
        .itemInputs('gtceu:phosphorus_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('4x kubejs:1k_me_storage_wafer')
        .circuit(1)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_4k_me_storage_wafer_phosphorus')
        .duration(500)
        .itemInputs('gtceu:phosphorus_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('4x kubejs:4k_me_storage_wafer')
        .circuit(2)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_16k_me_storage_wafer_phosphorus')
        .duration(500)
        .itemInputs('gtceu:phosphorus_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('4x kubejs:16k_me_storage_wafer')
        .circuit(3)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_64k_me_storage_wafer_phosphorus')
        .duration(500)
        .itemInputs('gtceu:phosphorus_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('4x kubejs:64k_me_storage_wafer')
        .circuit(4)
        .EUt(1920)

    //Silicon
    event.recipes.gtceu.laser_engraver('kubejs:engraving_1k_me_storage_wafer_silicon')
        .duration(900)
        .itemInputs('gtceu:silicon_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('kubejs:1k_me_storage_wafer')
        .circuit(1)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_4k_me_storage_wafer_silicon')
        .duration(900)
        .itemInputs('gtceu:silicon_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('kubejs:4k_me_storage_wafer')
        .circuit(2)
        .EUt(1920)

    event.recipes.gtceu.laser_engraver('kubejs:engraving_16k_me_storage_wafer_silicon')
        .duration(900)
        .itemInputs('gtceu:silicon_wafer')
        .notConsumable('#forge:lenses/certus')
        .itemOutputs('kubejs:16k_me_storage_wafer')
        .circuit(3)
        .EUt(1920)
})