ServerEvents.recipes(event => {
  event.recipes.gtceu.forming_press("printed_silicon")
    .notConsumable('ae2:silicon_press')
    .itemInputs('gtceu:silicon_plate')
    .itemOutputs('ae2:printed_silicon')
    .duration(200)
    .EUt(120)

  event.recipes.gtceu.forming_press("printed_logic_processor")
    .notConsumable('ae2:logic_processor_press')
    .itemInputs('gtceu:gold_plate')
    .itemOutputs('ae2:printed_logic_processor')
    .duration(200)
    .EUt(120)

  event.recipes.gtceu.forming_press("printed_engineering_processor")
    .notConsumable('ae2:engineering_processor_press')
    .itemInputs('gtceu:diamond_plate')
    .itemOutputs('ae2:printed_engineering_processor')
    .duration(200)
    .EUt(120)

  event.recipes.gtceu.forming_press("printed_calculation_processor")
    .notConsumable('ae2:calculation_processor_press')
    .itemInputs('gtceu:certus_quartz_plate')
    .itemOutputs('ae2:printed_calculation_processor')
    .duration(200)
    .EUt(120)

  event.recipes.gtceu.forming_press("printed_calculation_copy")
    .notConsumable('ae2:calculation_processor_press')
    .itemInputs('minecraft:iron_block')
    .itemOutputs('ae2:calculation_processor_press')
    .duration(100)
    .EUt(30)

  event.recipes.gtceu.forming_press("printed_logic_copy")
    .notConsumable('ae2:logic_processor_press')
    .itemInputs('minecraft:iron_block')
    .itemOutputs('ae2:logic_processor_press')
    .duration(100)
    .EUt(30)

  event.recipes.gtceu.forming_press("engineering_copy")
    .notConsumable('ae2:engineering_processor_press')
    .itemInputs('minecraft:iron_block')
    .itemOutputs('ae2:engineering_processor_press')
    .duration(100)
    .EUt(30)

  event.recipes.gtceu.forming_press("printed_silicon_copy")
    .notConsumable('ae2:silicon_press')
    .itemInputs('minecraft:iron_block')
    .itemOutputs('ae2:silicon_press')
    .duration(100)
    .EUt(30)
})
