ServerEvents.recipes( event => {
	
	event.remove({ id:'computercraft:cable' })
    event.recipes.gtceu.assembler('computercraft:cable')
        .itemInputs('gtceu:gold_single_cable', 'gtceu:red_alloy_tiny_dust')
        .itemOutputs('computercraft:cable')
        .duration(200)
        .EUt(120)
        .circuit(1)
    
    event.remove({ id:'computercraft:wired_modem' })
    event.recipes.gtceu.assembler('computercraft:wired_modem')
        .itemInputs('gtceu:lv_machine_casing', 'gtceu:plastic_circuit_board', '2x computercraft:cable', '#forge:circuits/mv')
        .inputFluids('gtceu:polyethylene 72')
        .itemOutputs('computercraft:wired_modem')
        .duration(200)
        .EUt(120)
        .circuit(1)
    
    event.remove({ id:'computercraft:wireless_modem_normal' })
    event.recipes.gtceu.assembler('computercraft:wireless_modem_normal')
        .itemInputs('gtceu:mv_machine_casing', 'gtceu:epoxy_circuit_board', '2x computercraft:cable', '#forge:circuits/hv', 'gtceu:mv_emitter', 'gtceu:mv_sensor')
        .inputFluids('gtceu:polyvinyl_chloride 72')
        .itemOutputs('computercraft:wireless_modem_normal')
        .duration(200)
        .EUt(256)
        .circuit(1)
    
    event.remove({ id:'computercraft:wireless_modem_advanced' })
    event.recipes.gtceu.assembler('computercraft:wireless_modem_advanced')
        .itemInputs('gtceu:hv_machine_casing', 'gtceu:fiber_reinforced_circuit_board', '2x computercraft:cable', '#forge:circuits/ev', 'gtceu:hv_emitter', 'gtceu:hv_sensor')
        .inputFluids('gtceu:polytetrafluoroethylene 72')
        .itemOutputs('computercraft:wireless_modem_advanced')
        .duration(200)
        .EUt(480)
        .circuit(1)
})