#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["gtceu", "minecraft", "tconstruct", "tmechworks", "create", "immersiveengineering", "mekanism", "thermal"]

