
#Game settings
[settings]
	#If enabled, players will be able to reel back rope, bottom to top, when sneak-using with an empty hand on them.
	enableRopeReeling = true
	#A list of dye colors that, when used as the background color of a Canvas Sign, should default to white text when placed.
	#Dyes: ["white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black"]
	canvasSignDarkBackgroundList = ["gray", "purple", "blue", "brown", "green", "red", "black"]
	#If enabled, Novice and Apprentice Farmer villagers will have a chance to buy crops from this mod.
	enableFarmerFDTrades = true
	#If enabled, the Wandering Trader will have a chance to sell seeds and plantables from this mod.
	enableWanderingTraderFDTrades = true

#Farming
[farming]
	#Which rope should Tomato Vines leave behind when broken?
	defaultTomatoVineRope = "farmersdelight:rope"
	#If enabled, tomato crops will be able to climb any rope tagged as farmersdelight:ropes. If disabled, this will be restricted to this mod's rope only.
	#Beware: this will convert these blocks into the block specified in defaultTomatoVineRope.
	enableTomatoVineClimbingTaggedRopes = true
	#The chance (in decimal percentage) of Rich Soil providing a bone meal boost to a crop planted on it. Set to 0.0 to disable.
	#Range: 0.0 ~ 1.0
	richSoilBoostChance = 0.2

#Vanilla item overrides
[overrides]
	#If enabled, soups and stews from Minecraft will grant Nourishment when eaten, similar to meals from this mod.
	enableVanillaSoupExtraEffects = true
	#If enabled, Rabbit Stew will grant users the jumping prowess of a rabbit when eaten.
	enableRabbitStewJumpBoost = true
	#If enabled, Pumpkin Pie will require the user to sneak to place it down as a block.
	enablePumpkinPieSneakToPlace = false
	#If enabled, the Dispenser will be able to operate a Cutting Board in front of itself, using stored items as cutting tools.
	enableCuttingBoardDispenserBehavior = true

	#Stack size overrides
	[overrides.stack_size]
		#If enabled, any BowlFoodItem in the following list become stackable to 16, much like Farmer's Delight's meals.
		enableStackableSoupItems = false
		#List of targeted food items. They must extend the BowlFoodItem class in code to be affected. Defaults to vanilla soups and stews.
		soupItemList = []

#World generation
[world]
	#If enabled, new loot pools will be added to chest loot across the game, containing items from this mod (ropes, crops, tools etc).
	generateFDChestLoot = true
	#If enabled, Compost Heaps (structures containing Organic Compost piles) will sometimes generate across Villages.
	generateVillageCompostHeaps = true
	#If enabled, crops from Farmer's Delight will sometimes replace standard crops in village farm plots.
	generateFDCropsOnVillageFarms = true

#Crafting
[crafting]
	#If enabled, the Cooking Pot will provide a Recipe Book on its interface, similar to the one on Crafting Tables and Furnaces.
	enableCookingPotRecipeBook = true
	#If enabled, storage crates (3x3) for vanilla crops (similar to Quark and Thermal Cultivation) will become craftable.
	enableVanillaCropCrates = true
	#How much (in decimal percentage) should each level of Fortune increase the odds of obtaining rare results on the Cutting Board? Set to 0.0 to disable.
	#Range: 0.0 ~ 1.0
	cuttingBoardFortuneBonus = 0.1

#Debug settings (Not meant for gameplay)
[debug]
	#Tomato crops hanging on rope will force-place a Rope block when broken. Due to technical limitations, this affects things such as commands, making them fail to 'setblock' at first.
	#Disable this if this block is preventing you from editing a region in creative or with commands. For normal gameplay, I recommend leaving this enabled.
	enableTomatoRopePermanence = true

