# Maximum stress capacity for ULS tier machines
ULS_CAPACITY: 8.0

# Maximum stress capacity for LS tier machines
LS_CAPACITY: 32.0

# Maximum stress capacity for MS tier machines
MS_CAPACITY: 128.0

# Maximum stress capacity for HS tier machines
HS_CAPACITY: 512.0

# Maximum stress capacity for ES tier machines
ES_CAPACITY: 2048.0

# Maximum stress capacity for IS tier machines
IS_CAPACITY: 8192.0

# Maximum stress capacity for LuS tier machines
LUS_CAPACITY: 32768.0

# Maximum stress capacity for ZPMS tier machines
ZPMS_CAPACITY: 131072.0

# Maximum stress capacity for US tier machines
US_CAPACITY: 524288.0

# Maximum stress capacity for UHS tier machines
UHS_CAPACITY: 2097152.0

