
#General settings
[General]
	#Dictates the 1 in X chance the Oreberry Bush grows every time it tries to grow [Default: 20]
	#Range: > 1
	growthChance = 20

#Placement settings
[Placement]
	#Only allow placing Iron Bushes in darkness [Default: true]
	darknessOnlyIronBush = true
	#Only allow placing Gold Bushes in darkness [Default: true]
	darknessOnlyGoldBush = true
	#Only allow placing Copper Bushes in darkness [Default: true]
	darknessOnlyCopperBush = true
	#Only allow placing Tin Bushes in darkness [Default: true]
	darknessOnlyTinBush = true
	#Only allow placing Aluminum Bushes in darkness [Default: true]
	darknessOnlyAluminumBush = true
	#Only allow placing Lead Bushes in darkness [Default: true]
	darknessOnlyLeadBush = true
	#Only allow placing Nickel Bushes in darkness [Default: true]
	darknessOnlyNickelBush = true
	#Only allow placing Uranium Bushes in darkness [Default: true]
	darknessOnlyUraniumBush = true
	#Only allow placing Osmium Bushes in darkness [Default: true]
	darknessOnlyOsmiumBush = true
	#Only allow placing Zinc Bushes in darkness [Default: true]
	darknessOnlyZincBush = true
	#Only allow placing Silver Bushes in darkness [Default: true]
	darknessOnlySilverBush = true
	#Only allow placing Essence Bushes in darkness [Default: true]
	darknessOnlyEssenceBush = true

#Density settings
[Density]
	#Iron Bush Density [Default: 1]
	#Range: 1 ~ 32
	ironBushDensity = 1
	#Gold Bush Density [Default: 1]
	#Range: 1 ~ 32
	goldBushDensity = 1
	#Copper Bush Density [Default: 2]
	#Range: 1 ~ 32
	copperBushDensity = 2
	#Tin Bush Density [Default: 2]
	#Range: 1 ~ 32
	tinBushDensity = 2
	#Aluminum Bush Density [Default: 2]
	#Range: 1 ~ 32
	aluminumBushDensity = 2
	#Lead Bush Density [Default: 1]
	#Range: 1 ~ 32
	leadBushDensity = 1
	#Nickel Bush Density [Default: 1]
	#Range: 1 ~ 32
	nickelBushDensity = 1
	#Uranium Bush Density [Default: 1]
	#Range: 1 ~ 32
	uraniumBushDensity = 1
	#Osmium Bush Density [Default: 1]
	#Range: 1 ~ 32
	osmiumBushDensity = 1
	#Zinc Bush Density [Default: 2]
	#Range: 1 ~ 32
	zincBushDensity = 2
	#Silver Bush Density [Default: 1]
	#Range: 1 ~ 32
	silverBushDensity = 1
	#Essence Bush Density [Default: 2]
	#Range: 1 ~ 32
	essenceBushDensity = 2

