name: Latest Build

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run : |
          chmod +x ./packwiz
      - run: |
          ./packwiz cf export -o GBTH.zip
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-dev
          files: GBTH.zip
          prerelease: true
